version: '2'
services:
  eurekaserver:
     image:   johncarnell/tmx-eurekasvr:chapter6v2
     ports:
       - "8761:8761"
  configserver:
      image: johncarnell/tmx-confsvr:chapter6v2
      ports:
         - "8888:8888"
      environment:
         EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
         EUREKASERVER_PORT: "8761"
         ENCRYPT_KEY:       "IMSYMMETRIC"
  database:
      image: postgres:9.5
      ports:
      - "5432:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=p0stgr@s
        - POSTGRES_DB=eagle_eye_local
  organizationservice:
    image: johncarnell/tmx-organization-service:chapter6v2
    ports:
      - "8085:8085"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8085"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  licensingservice:
    image: johncarnell/tmx-licensing-service:chapter6v2
    ports:
      - "8080:8080"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8080"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  zuulserver:
    image: johncarnell/tmx-zuulsvr:chapter6v2
    ports:
      - "5555:5555"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      DATABASESERVER_PORT:      "5432"
      CONFIGSERVER_PORT:        "8888"
      ORGSERVERNEW_PORT:        "8087"
  specialroutesservice:
    image: johncarnell/tmx-specialroutes-service:chapter6v2
    ports:
      - "8910:8910"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8910"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      DATABASESERVER_PORT:      "5432"
      CONFIGSERVER_PORT:        "8888"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  orgservice-new:
    image: johncarnell/tmx-orgservice-new:chapter6v2
    ports:
      - "8087:8087"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8087"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      DATABASESERVER_PORT:      "5432"
      CONFIGSERVER_PORT:        "8888"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  

    